### ISSUE TITLE
Do it with Next.js

### ISSUE THREAD

**Issue by metzgegu** [metzgegu/metzgegu.github.io#10]
I think it would be cool to do it with Next.js.

See example :
https://github.com/thierryc/Next-gh-page-example

**Comment by PierreBerger** [comment]
If it's okay for you I will open a PR as soon as I can

**Comment by PierreBerger** [comment]
Considering that #11 is merged you can closed this issue @metzgegu

**Comment by metzgegu** [comment]
Yes i'm closing this one, nice job @PierreBerger 🚀
