### ISSUE TITLE
Use typescript

### ISSUE THREAD

**Issue by PierreBerger** [metzgegu/metzgegu.github.io#13]
It would be nice to use typescript [Next JS migrate to typescript](https://nextjs.org/docs/basic-features/typescript)

**Comment by metzgegu** [comment]
I don't think it is really necessary, the website doesn't fetch much data

**Comment by PierreBerger** [comment]
As you want, imo Typescript is essential for any JS project for inscreasing code quality, flexibility and comprehension.

**Comment by metzgegu** [comment]
I close this one because it has been migrated in NextJS https://github.com/metzgegu/metzgegu-website/commit/01bf245c44cda35d3099bcff16325a0d7a0da698 and since it has been migrated to SvelteKit https://github.com/metzgegu/metzgegu-website/commit/099f6695ae0887e5ca3021bef9704565338ed847
