### ISSUE TITLE
Mobile optimization

### ISSUE THREAD

**Issue by PierreBerger** [metzgegu/metzgegu.github.io#7]
![IMG_4642](https://user-images.githubusercontent.com/16417858/94822754-4c830500-0403-11eb-9f8f-32136597c3a1.jpg)

This page could be more mobile friendly with a bigger font on little texts.

**Comment by metzgegu** [comment]
Yes you're right, feel free to suggest changes 👍

**Comment by PierreBerger** [comment]
Any news ?

**Comment by metzgegu** [comment]
This has been implemented in https://github.com/metzgegu/metzgegu-website/pull/27
<img width="614" alt="Capture d’écran 2024-10-11 à 12 29 38" src="https://github.com/user-attachments/assets/190fa58b-9e21-46a1-8054-7551a7878184">
