### ISSUE TITLE
SEO friendly

### ISSUE THREAD

**Issue by PierreBerger** [metzgegu/metzgegu.github.io#8]
There is no meta tag for SEO.

**Comment by metzgegu** [comment]
I just added the meta description in this commit : 92a5ef070b278de397e2ceb0d38bab7841bb1be9

Feel free to had more best practices to increase the SEO level

**Comment by PierreBerger** [comment]
I think #10 will help to improve the SEO

**Comment by metzgegu** [comment]
It depends, only if good practices are also implemented

**Comment by metzgegu** [comment]
The website appears on the first research page in google when researching my names, it is enough for me
